<a href="https://colab.research.google.com/github/TMV1982/Rebel-Power/blob/master/%D0%9A%D0%BE%D0%BF%D0%B8%D1%8F_%D0%B1%D0%BB%D0%BE%D0%BA%D0%BD%D0%BE%D1%82%D0%B0_%22Untitled7_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:

# Import TensorFlow
import tensorflow as tf

In [ ]:
# Check its version
tf.__version__

'2.4.1'

In [ ]:
# Train a feedforward neural network for image classification
print('Loading data...\n')
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.mnist.load_data()

Loading data...



In [ ]:
x_train = x_train/255.

In [ ]:
model = tf.keras.models.Sequential([
tf.keras.layers.Flatten(),
tf.keras.layers.Dense(16, activation='relu'),
tf.keras.layers.Dense(10, activation='softmax')                                    
])

In [ ]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
print('Training model...\n')
model.fit(x_train, y_train, epochs=30, batch_size=32)

Training model...

Epoch 1/30
1875/1875 [==============================] - 3s 1ms/step - loss: 0.7330 - accuracy: 0.7877
Epoch 2/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2535 - accuracy: 0.9272
Epoch 3/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.2077 - accuracy: 0.9399
Epoch 4/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1806 - accuracy: 0.9473
Epoch 5/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1640 - accuracy: 0.9531
Epoch 6/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1587 - accuracy: 0.9546
Epoch 7/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1506 - accuracy: 0.9574
Epoch 8/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1379 - accuracy: 0.9588
Epoch 9/30
1875/1875 [==============================] - 2s 1ms/step - loss: 0.1355 - accuracy: 0.9585
Epoch 10/30
1875/1875 [==============================] - 2s 1ms

In [ ]:
print('Model trained successfully!')

Model trained successfully!


In [ ]:
x_test.shape

(10000, 28, 28)

In [ ]:
a = tf.constant([1, 2, 3, 4, 5, 6], shape=[2, 3])

In [ ]:
b = tf.constant([7, 8, 9, 10, 11, 12], shape=[3, 2])

In [ ]:
b

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
c = tf.matmul(a,b)

In [ ]:
import numpy as np
a = tf.constant(np.arange(1, 13, dtype=np.int32), shape=[2, 2, 3])

In [ ]:
a

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]], dtype=int32)>

In [ ]:
b = tf.constant(np.arange(13, 25, dtype=np.int32), shape=[2, 3, 2])

In [ ]:
b

<tf.Tensor: shape=(2, 3, 2), dtype=int32, numpy=
array([[[13, 14],
        [15, 16],
        [17, 18]],

       [[19, 20],
        [21, 22],
        [23, 24]]], dtype=int32)>

In [ ]:
c = tf.matmul(a, b)

In [ ]:
c

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 94, 100],
        [229, 244]],

       [[508, 532],
        [697, 730]]], dtype=int32)>

In [ ]:
x = tf.Variable([1.,2.0], name='x')
print(x)

<tf.Variable 'x:0' shape=(2,) dtype=float32, numpy=array([1., 2.], dtype=float32)>
